[[redirects]]
  from = "/body-burn-west-ashley"
  to = "/body-burn"
  status = 301
  force = true

[[redirects]]
  from = "/summer-slim-down-challenge"
  to = "/specials"
  status = 301
  force = true

[[redirects]]
  from = "/summer-case-study1"
  to = "/specials"
  status = 301
  force = true

[[redirects]]
  from = "/summer-case-study2"
  to = "/specials"
  status = 301
  force = true

[[redirects]]
  from = "/summer-case-study3"
  to = "/specials"
  status = 301
  force = true

[[redirects]]
  from = "/summer-early-bird-form"
  to = "/specials"
  status = 301
  force = true

[[redirects]]
  from = "/summer-slim-thank-you"
  to = "/specials"
  status = 301
  force = true