[[redirects]]
  from = "/body-burn-west-ashley"
  to = "/body-burn"
  status = 301
  force = true

[[redirects]]
  from = "/summer-slim-down-challenge"
  to = "/specials"
  status = 301
  force = true

[[redirects]]
  from = "/summer-case-study1"
  to = "/specials"
  status = 301
  force = true

[[redirects]]
  from = "/summer-case-study2"
  to = "/specials"
  status = 301
  force = true

[[redirects]]
  from = "/summer-case-study3"
  to = "/specials"
  status = 301
  force = true

[[redirects]]
  from = "/summer-early-bird-form"
  to = "/specials"
  status = 301
  force = true

[[redirects]]
  from = "/summer-slim-thank-you"
  to = "/specials"
  status = 301
  force = true

[[redirects]]
  from = "/14-days-for-14-dollars-kick-start"
  to = "/14-for-14-new-member-special"
  status = 301
  force = true

[[redirects]]
  from = "/real-life-jennifer-fahey-stopped-yo-yo-dieting-and-became-stronger-than-ever"
  to = "/blog/jennifer-transformation-story"
  status = 301
  force = true

[[redirects]]
  from = "http://sleepy-cori-db5e31.netlify.com/"
  to = "http://thistimefitness.com/"
  status = 301
  force = true