export const siteConfig = {
  fbAppId: '734625066685760',
  home: {
    title: 'This Time Fitness: West Ashley Fitness Studio for Women',
    description:
      'Welcome to This Time Fitness. We are a West Ashley fitness studio for women. We focus on strength training, cardio, mobility, and overall healthy living.',
    url: 'https://thistimefitness.com',
    keywords: [
      'this time fitness',
      'charleston gym',
      'charleston personal trainer',
      'west ashley gym',
      'personal trainer west ashley',
    ],
    lang: 'en-us',
  },
  about: {
    title: 'About This Time Fitness',
    description: `Learn more about This Time Fitness and why it's the best studio in Charleston for you to hit your goals and learn about your body.`,
    url: 'https://thistimefitness.com/about',
    keywords: [
      'this time fitness',
      'charleston gym',
      'charleston personal trainer',
      'west ashley gym',
      'personal trainer west ashley',
    ],
    lang: 'en-us',
  },
  classes: {
    title: 'The Boot Camp & Group Fitness Classes TTF Offers',
    description: `We offer high intensity strength training classes that mix in cardio too. But we also offer running classes and yoga for a well rounded experience.`,
    url: 'https://thistimefitness.com/classes',
    keywords: [
      'boot camp fitness classes',
      'charleston gym',
      'group fitness classes',
      'west ashley gym',
      'body burn class',
    ],
    lang: 'en-us',
  },
  igniteProgram: {
    title: 'Ignite - 6 Week Beginner Focused Fitness Program',
    description: `Ignite is a 6 week program for women just getting back into exercise. We'll work with you extra close so you know what to do. Plus you get a lot more!`,
    url: 'https://thistimefitness.com/ignite',
    keywords: [
      'beginner fitness',
      'exercsie for beginners',
      'getting back into exercise',
      'west ashley gym',
      'ignite program',
    ],
    lang: 'en-us',
  },
  bodyBurn: {
    title: 'Body Burn High Intensity Strength Training',
    description: `Body Burn is our main class. It's a strength class with plenty of cardio. It's functional training designed to burn fat and get you strong. Learn more.`,
    url: 'https://thistimefitness.com/body-burn',
    keywords: [
      'high intensity training',
      'body burn class',
      'strength training for women',
      'west ashley gym',
    ],
    lang: 'en-us',
  },
  need4Speed: {
    title: 'Need 4 Speed Running Training',
    description: `Need 4 Speed is a running training class for all levels. You'll learn how to run with better form... with less injury... and faster. Learn more today.`,
    url: 'https://thistimefitness.com/need-for-speed',
    keywords: [
      'learn to run',
      'running training',
      'run without injury',
      'west ashley gym',
    ],
    lang: 'en-us',
  },
  weekendRecovery: {
    title: 'Weekend Recovery is Body Burn and Yoga Together',
    description: `Weekend Recovery adds in an optional yoga class on Saturday and Sunday. It's the best way to recovery and work on your mobility. Learn more.`,
    url: 'https://thistimefitness.com/weekend-recovery',
    keywords: [
      'yoga',
      'weekend fitness classes',
      'stretching and mobility',
      'west ashley gym',
    ],
    lang: 'en-us',
  },
  specials: {
    title: 'New Member Specials and Trials',
    description: `We offer a couple different ways for you to come try This Time Fitness. Learn about all of our options and start getting in the best shape you've ever been.`,
    url: 'https://thistimefitness.com/specials',
    keywords: [
      'fitness specials',
      '14 day trial',
      'new member programs',
      'west ashley gym',
    ],
    lang: 'en-us',
  },
  caseStudies: {
    title: 'Learn From Some Of Our Most Successful Members',
    description: `We have members who have worked really hard and completely changed their body and life. Here are their secrets, tips, and ideas so you can succeed too.`,
    url: 'https://thistimefitness.com/case-studies',
    keywords: [
      'fitness success stories',
      'weight loss case studies',
      'weight loss success stories',
      'west ashley gym',
    ],
    lang: 'en-us',
  },
  fourteen: {
    title: 'Come Try 14 Days of Unlimited Classes for Only $14',
    description: `Come try our Body Burn class, Need 4 Speed, Yoga, and meet the trainers. You get unlimited classes for only $14. Come see what group fitness should be.`,
    url: 'https://thistimefitness.com/14-for-14-new-member-special',
    keywords: [
      '14 day trial',
      'fitness trial',
      'this time fitness',
      'west ashley gym',
    ],
    lang: 'en-us',
  },
  location: {
    title: 'We Are Located Right Down The Street From You',
    description: `We are located at 2408 Ashley River Rd. It's off of highway 61 in West Ashley and close to you. Come visit us today!`,
    url: 'https://thistimefitness.com/location',
    keywords: [
      'location',
      'gym location',
      'west ashley fitness',
      'west ashley gym',
    ],
    lang: 'en-us',
  },
  pricing: {
    title: 'Find The Membership Option That Works For Your Budget',
    description: `We offer many different membership options. You will find one that works for you budget. And we guarantee to deliver the best training in workouts in Charleston.`,
    url: 'https://thistimefitness.com/pricing',
    lang: 'en-us',
  },
  schedule: {
    title: 'This Time Fitness Has A HUGE Class Schedule',
    description: `We offer a huge class schedule of over 27 weekly classes. You will find the perfect class for you so you can get strong and in the best shape of your life.`,
    url: 'https://thistimefitness.com/schedule',
    lang: 'en-us',
  },
  transformations: {
    title: 'See The Amazing Transformations From Our Amazing Members',
    description: `Here are some before and after pictures from real members of our studio. These women worked hard and got the results they wanted. You can too!`,
    url: 'https://thistimefitness.com/transformations',
    keywords: [
      'fitness success stories',
      'before and after pictures',
      'weight loss success pictures',
      'west ashley gym',
    ],
    lang: 'en-us',
  },
  reviews: {
    title: 'See What Some of Our Members Have to Say',
    description: `We are blessed with some amazing members. Here are just some of our members and what they said about working out at This Time Fitness.`,
    image: '../images/Facebook/14-for-14-share-image.jpg',
    url: 'https://thistimefitness.com/reviews',
    lang: 'en-us',
  },
  blog: {
    title: 'Learn the Tips, Tricks, And Successes That Help You Succeed!',
    description: `We share recipes, our workout tips, exercises, and case studies from our successful members so you can get the info to help you hit your healthy lifestyle goals.`,
    url: 'https://thistimefitness.com/blog',
    keywords: [
      'fitness blog',
      'healthy living tips',
      'fitness tips',
      'west ashley gym',
    ],
    lang: 'en-us',
  },
  ignite: {
    countdownDate: '05/13/2019 12:00 AM',
  },
  summerSlimDown: {
    countdownDate: '06/10/2019 12:00 AM',
    title: 'This Time Fitness Summer Slim Down Challenge',
    description: `The Summer Slim Down Challenge is an 8 week program to help you burn fat, get strong, and feel incredible over the summer. Are you ready for the best summer yet?`,
    url: 'https://thistimefitness.com/summer-slim-down-challenge',
    image: '../images/Facebook/summer-slim-down-share-image.jpg',
    keywords: [
      'this time fitness',
      'charleston gym',
      'charleston personal trainer',
      'west ashley gym',
      'personal trainer west ashley',
    ],
    lang: 'en-us',
  },
  purchaseLinks: {
    eightPerMonth: `https://thistimefitness.sites.zenplanner.com/registration.cfm?payment=MEMBERSHIP&MembershipTemplateId=F4D3E520-8DE8-4F31-A1E0-B4CFEFC2866D&personId=56B20BB1-7E56-4266-85AE-06304AD82AF1`,
    twelvePerMonth: `https://thistimefitness.sites.zenplanner.com/registration.cfm?payment=MEMBERSHIP&MembershipTemplateId=62022540-7CF8-4E99-B7E0-15C66510AB58&personId=B2D98D37-BD76-4F80-BF57-BEE23A2636FF`,
    unlimitedPerMonth: `https://thistimefitness.sites.zenplanner.com/registration.cfm?payment=MEMBERSHIP&MembershipTemplateId=608B67A4-9AB1-4BCF-8E06-298E9AD9DE79&personId=A48B0B9B-D5CA-4728-9FEE-D6EEAC7EB7C7`,
    fiveClassPass: `https://thistimefitness.sites.zenplanner.com/retail-product.cfm?ProductId=229BEDA9-9586-4CA6-8EC5-176B62DC6F72`,
    tenClassPass: `https://thistimefitness.sites.zenplanner.com/retail-product.cfm?ProductId=AE2FADB5-ACEF-4E16-AE04-D11782AF82E9`,
    fifteenClassPass: `https://thistimefitness.sites.zenplanner.com/retail-product.cfm?ProductId=F7120BB2-A086-4752-816E-D3B16202CFB9`,
  },
  siteWidths: {
    desktopNavWidth: 960,
  },
}
